name: Code Analysis
on:
  push:
    branches:
      - main
jobs:
  quality:
    name: Lint and format check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Format check and lint
        run: |
          npm ci
          npm run lint && npm run format:check
